travis:
  secure:
    BINSTAR_TOKEN: pJ0xgVlTPo6QcEFb68DxwZI54qXq8Kfe8G3GaRkQDeSNpjtTnHh0BeYUCakiH0EahTDpyxOgkygdDBVZiiAJq7Y+4NA0uBHocyIdrIntItufCQ2vfhxWd6J81PAAnSQRuqEuscEMI9rJrBQLmAVJXzU+qQr1mzaxbmO4oAVbQpYQ0rbMl8glNQ1kq4jBfzC/79Y+H0rdeyS30xLsv9NI9m/dmRCcset83CftXjDf/GzDkOZ0o7sWmSJkYKY2R9RKqvGmYJ0/7FQyZRVAQeIk3eTfHXGyOVdSwcUhv86QnkiCI2bnD3iEIG3RUsKY1GERbLcmTU6oqb9Bsp1kLyzPe454vNSQVZrRNAqa4qSZ09FN0Z329MRJqTb21guKo9KrOL4lNGYH72dF4EBZpjqPcCFK/Chk8ZltrDJY1JTZQn8PGKg0DzxDT/+nfOqK8FDAARbYe038P7PKQyBMJN/aPeh+BerGKQ2DH14VVa4CAgssFyuIWUVOF7JvgrySkNjV8gmy7xAm9W1APak0bjjXjkYXBwbXI/OPMYFRyJu4GzmMicyPZM7JIh1RDROOJp7Q7RzdHCEgggQ9C5u/V6oD2WgxQ3J8kxYcyPG+Av5iiB05nCP70IEeyCbIK+eAwL7BSHulmoNVNnRnBmxQehtne2jg/KWSK9y1HZhCtSnYahg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
